name: CI Pipeline
on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install
      - name: Run a test
        run: npm test
      - name: Check coverage
        run: npm run coverage
      - name: Check codestyle
        run: npm run lint
